apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wordpressns
resources:
        - mysql-service.yaml
        - ns.yaml
        - pvc-mysql.yaml
        - pvc-wordpress.yaml
        - pv-nfs.yaml
        - pv-nfs-db.yaml
        - secret.yaml
        - wordpress-deploy.yaml
        - wordpress-service.yaml
        - ingress.yaml
        - mysql-deploy.yaml

          #images:
          #  - name: wordpress
          #    newTag: 5.7-php8.0-apache
